export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_FAILED = 'PRODUCTS_FAILED';

export const ADD_CLIENTS = 'ADD_CLIENTS';
export const CLIENTS_LOADING = 'CLIENTS_LOADING';
export const CLIENTS_FAILED = 'CLIENTS_FAILED';